name: 云端自动打包 EXE

on:
  workflow_dispatch:

jobs:
  build-windows-app:
    runs-on: windows-latest
    
    steps:
      - name: 1. 获取代码
        uses: actions/checkout@v4
        
      - name: 2. 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: 3. 安装依赖
        run: |
          npm install --legacy-peer-deps
          npm install electron electron-builder --save-dev --legacy-peer-deps
          
      - name: 4. 编译前端
        run: npm run build
        
      - name: 5. 打包 EXE
        run: npx electron-builder --win --dir
        
      - name: 6. 提取下载包
        uses: actions/upload-artifact@v4
        with:
          name: 打包完成的桌面程序
          path: dist/win-unpacked/
